services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: liquido_db_user
      QUARKUS_DATASOURCE_PASSWORD: liquido_db_pass25
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/liquido_dev

  db:
    image: postgres:15-alpine
    container_name: liquido-postgres
    restart: always
    environment:
      POSTGRES_USER: liquido_db_user
      POSTGRES_PASSWORD: liquido_db_pass25
      POSTGRES_DB: liquido_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   # Persist data across restarts

volumes:
  postgres_data: