services:
  app:
    container_name: liquido-backend
    image: liquido-backend:latest
    platform: linux/amd64  # Ensures it runs on an x86_64 machine
    env_file: # load environment variables already necessary for build stage
      - .env
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:  # pass values from .env file into build stage
        QUARKUS_DATASOURCE_DB_KIND:  ${QUARKUS_DATASOURCE_DB_KIND}
        QUARKUS_DATASOURCE_USERNAME: ${QUARKUS_DATASOURCE_USERNAME}
        QUARKUS_DATASOURCE_PASSWORD: ${QUARKUS_DATASOURCE_PASSWORD}
        QUARKUS_DATASOURCE_JDBC_URL: ${QUARKUS_DATASOURCE_JDBC_URL}
    environment:
      - QUARKUS_CONFIG_LOCATIONS=/app/config/
      - QUARKUS_PROFILE=dev  # Forces Quarkus to use application-dev.properties
    ports:
      - "8080:8080"
    volumes:
      - ~/m2:/root/.m2   # persist maven cache
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: liquido-postgres
    restart: always
    environment:
      POSTGRES_USER: ${QUARKUS_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${QUARKUS_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-liquido_dev}
    ports:
      - "5432:5432"
    volumes:
      - liquido_postgres:/var/lib/postgresql/data   # Persist data across restarts

volumes:
  liquido_postgres: