#!/usr/bin/env python3
"""
Check the whitepaper's internal cross-reference links.

Every reference to another part of the document is a markdown link to a heading anchor,
so that it works both on GitHub and in the page generated by build-whitepaper.py. That
only holds if three things are true, and each has failed silently at least once:

  1. No two headings slug to the same anchor. GitHub would append "-1" to the second one
     and the link would land on the wrong section.
  2. Every link target resolves to a heading that exists.
  3. Every link points at the section its own text names. A link reading "Section 5.3"
     that resolves to 5.2 passes checks 1 and 2 and is still wrong; renumbering has
     produced exactly this three times, which is why the audit below is not optional.

It also reports references written as plain text, since those are the ones that were
missed rather than deliberately left alone.

    python3 docs/check-whitepaper-links.py docs/liquido-whitepaper.md [--verbose]
"""
import re
import sys
from collections import Counter

# build-whitepaper.py is not a legal module name, so it is loaded by path. Sharing its
# slug() is the point: a checker with its own copy could agree with itself and disagree
# with the generator.
import importlib.util
_spec = importlib.util.spec_from_file_location(
    "wp_build", __file__.rsplit("/", 1)[0] + "/build-whitepaper.py")
_build = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_build)
slug = _build.slug

HEADING = re.compile(r"^(#{1,4})\s+(.*)$")
LINK = re.compile(r"\[([^\]]+)\]\(#([^)]+)\)")
# "Section 5.3", "Chapter 10", "Part III" written as bare prose
BARE = re.compile(r"(?<!\[)\b(Sections?|Chapters?|Parts?)\s+([0-9IVX]+(?:\.[0-9]+)?)\b")


def headings(md):
    """(level, title, slug) for every heading, in document order."""
    out, in_fence = [], False
    for line in md.split("\n"):
        if line.strip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = HEADING.match(line.strip())
        if m:
            out.append((len(m.group(1)), m.group(2).strip(), slug(m.group(2).strip())))
    return out


def main():
    path = sys.argv[1]
    verbose = "--verbose" in sys.argv
    md = open(path, encoding="utf-8").read()

    heads = headings(md)
    by_slug = {s: t for _, t, s in heads}
    errors = []

    # 0. a heading must not itself contain a link. A bulk rewrite of references once
    #    reached into the heading lines; the anchors still resolved, because slug()
    #    reduces a link to its text, so nothing else here would have caught it.
    for _, title, _ in heads:
        if LINK.search(title):
            errors.append(f"LINK IN HEADING   {title}")

    # 1. duplicate anchors
    for s, n in Counter(s for _, _, s in heads).items():
        if n > 1:
            errors.append(f"DUPLICATE ANCHOR  #{s} is generated by {n} headings")

    # 2 + 3. resolvable, and pointing where the link text says
    audit = []
    for text, target in LINK.findall(md):
        if target not in by_slug:
            errors.append(f"DEAD LINK         [{text}](#{target})")
            continue
        title = by_slug[target]
        num = re.search(r"\b([0-9]+(?:\.[0-9]+)?)\b", text)
        ok = True
        if num:
            # the target's own leading number must be the one the link text names
            tnum = re.match(r"\s*([0-9]+(?:\.[0-9]+)?)[.\s]", title + " ")
            ok = bool(tnum) and tnum.group(1) == num.group(1)
        elif text.strip().lower().startswith("part"):
            ok = title.lower().startswith(text.strip().lower())
        if not ok:
            errors.append(f"WRONG TARGET      [{text}] resolves to \"{title}\"")
        audit.append(("ok " if ok else "BAD", text, title))

    # 4. references left as plain text
    # Cut the Changelog first: stripping headings would remove the marker it is found by.
    body = md[: md.index("## Changelog")] if "## Changelog" in md else md
    body = "\n".join(l for l in body.split("\n") if not HEADING.match(l.strip()))
    body = LINK.sub("", body)
    bare = sorted(set(f"{m.group(1)} {m.group(2)}" for m in BARE.finditer(body)))

    if verbose:
        for state, text, title in audit:
            print(f"  {state}  {text:<24} -> {title}")

    print(f"{len(heads)} headings, {len(audit)} internal links checked")
    if bare:
        print(f"\n{len(bare)} reference(s) still written as plain text:")
        for b in bare:
            print(f"  {b}")
    if errors:
        print()
        for e in errors:
            print(e)
        print(f"\nFAILED: {len(errors)} problem(s)")
        return 1
    print("OK: anchors unique, every link resolves, every link points at the section it names")
    return 0


if __name__ == "__main__":
    sys.exit(main())
