@startuml

' skin rose

title LIQUIDO Register & Login

start

:**""Open URL: /""**;

if (\nIs user authenticated\nwith JWT from localStorage?\n) then (yes)

  :**Automatic login**

  validate JWT;

  :If user has a not yet
  verified auth Factor
  then offer to verify it.;

elseif (/login)

  :**""URL: /login""**

  Choose login method;

  :If user has a not yet
  verified auth Factor
  then offer to verify it.;

else (/register)

  :**""URL: /register""**

  Chatbot asks for username;

  if (\nCreate a new team or\njoin an existing one?\n) then (create new team)

    :Create a new team
     * teamname
     * email
     * mobilephone;

  else (join a team)

    :Join an existing team
     * inviteCode
     * email
     * mobilephone;

  endif

  :Liquido backend creates a new AuthFactor

  ""TwilioVerifyService.register(user)"";

  :user's device now already has a JWT\nStored in browser's localStorage.\nIf the process is interrupted here\nthen he can continue via one of the left logins.}

  :User now installs Authy app;

  :User validates Factor with first authToken from Authy App

  ""TwilioVerifyService.verifyFactor(user, authToken)"";

endif

stop

note right
  User is logged in
end note

@enduml