@startuml

' skin rose

title LIQUIDO Register & Login

start

:**""Open URL: /""**;

if (\nIs user authenticated\nwith JWT from localStorage?\n) then (yes)

  :validate JWT;

  :If user has a not yet
  verified auth Factor
  then offer to verify it.;

elseif (/login)

  :**""URL: /login""**
  enter username and password;

  :If user has a not yet
  verified auth Factor
  then offer to verify it.;

else (/register)

  :**""URL: /register""**
  ask for username;

  if (\nCreate a new team or\njoin an existing one?\n) then (create new team)

    :Create a new team
     * teamname
     * email
     * mobilephone;

  else (join a team)

    :Join an existing team
     * inviteCode
     * email
     * mobilephone;

  endif

  :user now has a JWT\nif process is interrupted here\nthen can continue via the left path.}

  :Create new auth Factor
  ""TwilioVerifyService.register(user)"";

  :User validates Factor with first authToken from Authy App
  ""TwilioVerifyService.verifyFactor(user, authToken)"";

endif

stop

note right
  User is logged in
end note

@enduml