@startuml

' skin rose

title LIQUIDO Register & Login

start

:Open app "/";

note right
  fetch JWT from localStorage
end note

switch (Is user authenticated?)

case (yes\nauthenticated)

  :validate JWT;

  :If user has a not yet
  verified auth Factor
  then offer to verify it.;

case (no, but user\nclicks "login" Link)

  :login page;

  :If user has a not yet
  verified auth Factor
  then offer to verify it.;

case (no, anonymous call)

  :ask for username;

  if (Create a new team or\njoin an existing one?) then (create new team)

    :Create a new team
     * teamname
     * email
     * mobilephone;

  else (join a team)

    :Join an existing team
     * inviteCode
     * email
     * mobilephone;

  endif

  :user now has a JWT\nif process is interrupted here\nthen can continue via the left path.}

  :Create new auth Factor
  ""TwilioVerifyService.register(user)"";

  :User validates Factor with first authToken from Authy App
  ""TwilioVerifyService.verifyFactor(user, authToken)"";

endswitch

stop

note right
  User is logged in
end note

@enduml